### ISSUE TITLE
Question about the details

### ISSUE THREAD

**Issue by CoinCheung** [Kid-key/MimicNorm#1]
https://github.com/Kid-key/MimicNorm/blob/21eb0c9a69bd8811f7c7d541e10c258faeb23c39/ImageNet/models/resnet_nobn.py#L82

Hi, 

There are two things that makes the method work: One is to initializa the weight to be `sqrt(2., n)`, and the other is to add a bn layer after the model output. If there are residual structures, a learnable scale layer should be added before the shortcuts. Am I correct in the understanding of your method ?

**Comment by Kid-key** [comment]
Emmm, not like that. The first modification is weight mean, as elaborated in the 'meanweigh' function on 'main.py' file. As for the initialization, we enlarge the initial variance to about 1.2*sqrt(2./ n) to meet the theoretical requirement.

**Comment by CoinCheung** [comment]
So what makes the method work are: 1. subtract mean of kernel weight; 2. last bn; 3. learnable scale factor( if there is residual structure); Am I right this time ?

**Comment by Kid-key** [comment]
correct, mostly it works, however, we recommend a warmup strategy about 1-2 epochs to keep stable.

**Comment by CoinCheung** [comment]
Thanks for replying !!! I am closing this.
